### ISSUE TITLE
Game crashing when trying to play

### ISSUE THREAD

**Issue by vizthex123** [dbjorge/jorbs-spire-mod#407] opened 2020-02-14 22:57 UTC
**Version**
Slay the spire: Main
Mod version: Workshop doesn't say, but I guess Feb 14 @ 14:19 PM (CST)?

**Describe the bug**
Can't play as the Wanderer. I think it's probably something in my modpack (https://steamcommunity.com/sharedfiles/filedetails/?id=1614381293) but I'm not sure

**Comment by dbjorge** [comment] 2020-02-14 23:28
I am able to successfully load the game and start a wanderer run with the set of mods you've mentioned enabled:

![image](https://user-images.githubusercontent.com/376284/74576030-1e1cec00-4f3e-11ea-82c8-da284004d881.png)

Are you, by chance, using French for your language setting? There was a bug prior to version v1.0.2 on the workshop that would crash if you started in French; it should be fixed if you let the workshop update to the latest version.

If that isn't it, we're going to need more logs to diagnose this any further, since I can't reproduce the crash with the mods you're using. If you could zip up the `sendToDevs` folder in your Slay the Spire installation folder (usually you'll find it at somewhere like `C:\Program Files (x86)\Steam\steamapps\common\SlayTheSpire\sendToDevs`) and upload it somewhere we can look at it, we'd be happy to investigate further

**Comment by dbjorge** [comment] 2020-02-17 18:49
Since we haven't heard back and still don't have a means to reproduce, closing this for now. @vizthex123, if you are able to pass along a crash log, feel free to reopen this and we'd be happy to take a look!

**Closed by dbjorge** 2020-02-17 18:49 UTC
Labels: bug, can't reproduce
