### ISSUE TITLE
Give memory descriptions indication of on-remember and on-forget effects

### ISSUE THREAD

**Issue by wang429** [dbjorge/jorbs-spire-mod#205] opened 2019-11-27 03:02 UTC
It can be confusing why some effect occur when changing memories.

**Comment by dbjorge** [comment] 2019-11-27 04:32
Duplicate of #174

**Closed by dbjorge** 2019-11-27 04:32 UTC
Labels: Character: Wanderer, enhancement

**Comment by wang429** [comment] 2019-11-27 04:45
This is what happens when your brain is breaking while learning Javassist
