### ISSUE TITLE
mirror image debuffs from the memories don't seem to go be mirrored

### ISSUE THREAD

**Issue by wang429** [dbjorge/jorbs-spire-mod#135] opened 2019-11-11 22:58 UTC
See Discord message by Socien#9742 https://discordapp.com/channels/329758756076519436/638464764863053851/643579196412657685

**Comment by ImprovPanda** [comment] 2019-11-12 22:38
When magic mirror is applied, debuffs from Memories are not applied to enemies. if this is intended to be only applied to debuffs from enemies, wording could be changed on magic mirror.

**Comment by dbjorge** [comment] 2019-11-13 08:41
by design (doing all debuffs would be too strong in combination with snap giving -str debuffs for charity/temperance). Will update card text to clarify.

**Comment by dbjorge** [comment] 2019-11-13 08:44
Wording fixed by 41ecee1

![image](https://user-images.githubusercontent.com/376284/68747082-ae017180-05ae-11ea-8d6c-9a314f4c91d5.png)

**Closed by dbjorge** 2019-11-13 08:44 UTC
Labels: Character: Wanderer, bug, question
