### ISSUE TITLE
Magic Mirror: some reflected debuffs don't support being applied to enemies

### ISSUE THREAD

**Issue by squid-lee** [dbjorge/jorbs-spire-mod#171] opened 2019-11-17 12:52 UTC
Tracking list of powers to patch to support being on an enemy (or if not possible, to exclude from being mirrored):

* [x] `EntanglePower` (from #146 ): needs discussion in discord on desired effect. Options include "at start of turn, if enemy chose an attack intent, change to stun" or "...increment move choice"
* [x] `HexPower`: patch `HexPower.onUseCard` to only take effect if `this.owner.isPlayer`
* [x] `DrawReductionPower`: From Time Eater. Needs discussion on desired effect. Player will draw 2 less cards total
* [x] `ConstrictedPower`: Spire Growth's Constricted doesn't get reflected
* [x] `ConfusionPower`: Snecko's Confusion doesn't really do anything. Probably OK, but maybe patch only only take effect if `this.owner.isPlayer`

--- original report below ---
Play magic mirror, get hexed, receive 2x daze per non-attack card.

**Comment by wang429** [comment] 2019-11-17 16:12
I think I've seen this before for powers that the devs didn't intend to apply to either players or monsters. For example, there's a mod I remember I was watching that allowed for copying the power bar of a monster. In this case, the streamer cloned the heart's powers, including beat of death. subsequent cards dealt 2x damage to play

**Comment by wang429** [comment] 2019-11-17 16:13
The issue is more general where powers will specifically reference `AbstractDungeon.player` for some effects

**Comment by dbjorge** [comment] 2019-11-17 16:42
Yes, #146 is another variation of the same general issue. Probably the best immediate workaround would be to maintain a list of power IDs that magic mirror should avoid mirroring

**Comment by ImprovPanda** [comment] 2019-11-18 06:22
Probably intuitive but this applies through artifact charges as well.

**Comment by dbjorge** [comment] 2019-11-24 03:33
Fixed by ca26862

**Closed by dbjorge** 2019-11-24 03:33 UTC
Labels: Character: Wanderer, bug
