### ISSUE TITLE
Gluttony procs on Slime boss splits  

### ISSUE THREAD

**Issue by ImprovPanda** [dbjorge/jorbs-spire-mod#150] opened 2019-11-14 07:22 UTC
when you have gluttony going each time slime boss splits you get the +2 max hp

**Comment by ImprovPanda** [comment] 2019-11-14 07:23
This feels like a known issue but i didn't see it on the any of the open threads

**Comment by dbjorge** [comment] 2019-11-14 07:31
Duplicate of #86

**Comment by dbjorge** [comment] 2019-11-14 07:32
Duplicate of #86

**Closed by dbjorge** 2019-11-14 07:31 UTC
Labels: duplicate
