### ISSUE TITLE
Big with 'Fear' Spell

### ISSUE THREAD

**Issue by MirrorBi** [dbjorge/jorbs-spire-mod#198] opened 2019-11-24 06:51 UTC
When cast on a Darkling (little black life-link orbs in Act 3), it causes one to run away. but as long as that one's alive, the others can't be killed.

**Comment by dbjorge** [comment] 2019-11-24 06:53
This was already filed as #142 and should be fixed as of v0.40.0. Can you check and confirm which version of the mod you're playing with?

**Comment by dbjorge** [comment] 2019-11-27 22:04
Verified that this still works in current version. Since there hasn't been a response in a few days, I'm going to close this under the assumption that it was filed against an old version of the mod, but if you are able to reproduce it with a current version please feel free to re-open the issue!

**Closed by dbjorge** 2019-11-27 22:04 UTC
Labels: Character: Wanderer, bug, can't reproduce, duplicate
