### ISSUE TITLE
Mirror image "missed" attack still damages block

### ISSUE THREAD

**Issue by Rindokisuto** [dbjorge/jorbs-spire-mod#182] opened 2019-11-18 04:49 UTC
Confirmed I was not taking any health damage but my block was still going down.  Unless this is on purpose? but it doesn't seem to work how I thought a "missed" attack would

**Comment by dbjorge** [comment] 2019-11-18 05:13
Duplicate of #55 , wontfixing in favor of #68

**Closed by dbjorge** 2019-11-18 05:13 UTC
Labels: bug, duplicate
